name: Build, Run and Export Artifact from Docker

on:
  push:
  workflow_dispatch:

jobs:
  build-run-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myimage:latest .

      - name: Show total Docker image size
        run: docker images myimage:latest

      - name: Show Docker image layers and their sizes
        run: docker history --no-trunc --human myimage:latest

      - name: Create data directory (if needed)
        run: |
          mkdir ${{ github.workspace }}/volume
          chmod 777 ${{ github.workspace }}/volume

      - name: Run command in Docker container and copy file out
        run: |
          docker run -d --name mycontainer -v "${{ github.workspace }}/volume:/mnt/volume" myimage:latest sleep infinity

          docker exec mycontainer whoami
          docker exec mycontainer sh -c 'echo "hello" > /tmp/hello.txt'
          docker exec -w /mnt/volume mycontainer setup-volume.sh
          docker exec -w /mnt/volume/OsmAnd-submodules mycontainer ./prebuild.sh "5.1.3" "5103" arm64
          docker exec -w /mnt/volume/OsmAnd-submodules mycontainer ./build.sh arm64
          docker exec -w /mnt/volume/OsmAnd-submodules/android/OsmAnd mycontainer gradle assembleAndroidFullOpenglArm64Release

          docker stop mycontainer

          docker cp mycontainer:/tmp/hello.txt .
          docker rm mycontainer

      - name: Upload hello.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-file
          path: hello.txt
