name: fdroid build

on:
  push:
  workflow_dispatch:

jobs:
  show-system-info:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        #continue-on-error: true
        uses: actions/checkout@v4

      - name: whoami
        #continue-on-error: true
        run: whoami

      - name: Show current working directory
        #continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        #continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show CPU information
        #continue-on-error: true
        run: |
          echo "### CPU information:"
          lscpu

      - name: Show disk space
        #continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        #continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: lsb_release
        #continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a

      - name: apt
        #continue-on-error: true
        run: |
          echo "### apt:"
          sudo apt-get update
          sudo apt-get dist-upgrade

      - name: Show directory structure from root
        #continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 2:"
          sudo tree -L 2 /
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
      options: --user vagrant

    steps:
      - name: whoami
        #continue-on-error: true
        run: |
          ls -l /
          whoami
          echo "HOME:" $HOME
          ls -lad $HOME
          echo "Show all env:"
          printenv

      - name: Fix HOME permissions
        run: |
          sudo chown -R $(id -u):$(id -g) $HOME
          ls -la $HOME

      - name: Set permissions GITHUB_WORKSPACE
        run: |
          ls -ld $GITHUB_WORKSPACE
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          ls -ld $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE

      #- name: Set permissions RUNNER_TEMP
      #  continue-on-error: true
      #  run: |
      #    ls -ld $RUNNER_TEMP
      #    sudo chown -R $(id -u):$(id -g) $RUNNER_TEMP
      #    ls -ld $RUNNER_TEMP
      #    ls -la $RUNNER_TEMP

      - name: Show GITHUB_WORKSPACE
        #continue-on-error: true
        run: echo $GITHUB_WORKSPACE

      - name: ls GITHUB_WORKSPACE
        #continue-on-error: true
        run: ls -l $GITHUB_WORKSPACE

      - name: Show RUNNER_TEMP
        #continue-on-error: true
        run: echo $RUNNER_TEMP

      - name: ls RUNNER_TEMP
        #continue-on-error: true
        run: ls -l $RUNNER_TEMP

      - name: Set environment variables
        run: |
          echo "GITHUB_ENV:" $GITHUB_ENV
          sudo sh -c 'echo "ANDROID_HOME=/opt/android-sdk" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "ANDROID_HOME=/opt/android-sdk" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "ANDROID_SDK=/opt/android-sdk" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "ANDROID_NDK=/opt/android-sdk/ndk/23.2.8568313" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "FDROIDSERVER=/home/vagrant/fdroidserver" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "PATH=/opt/gradle/bin:/home/vagrant/fdroidserver:${PATH}" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "PYTHONPATH=/home/vagrant/fdroidserver:/home/vagrant/fdroidserver/examples" >> '"$GITHUB_ENV"
          sudo sh -c 'echo "PYTHONUNBUFFERED=true" >> '"$GITHUB_ENV"
          #sudo sh -c 'echo "GRADLE_OPTS=-Xmx4096m" >> '"$GITHUB_ENV"

          HOME_NEW=$(getent passwd $(whoami) | cut -d: -f6)
          echo "new HOME: $HOME_NEW"
          sudo sh -c "echo HOME=$HOME_NEW >> $GITHUB_ENV"

      #- name: Checkout repository
        #continue-on-error: true
        #uses: actions/checkout@v4

      - name: Checkout repository manually as non-root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git fetch --depth=1 origin $GITHUB_SHA
          git checkout $GITHUB_SHA

      - name: Write hello.txt
        #continue-on-error: true
        run: echo "Hello" > $GITHUB_WORKSPACE/hello.txt

      - name: ls GITHUB_WORKSPACE
        #continue-on-error: true
        run: ls -l $GITHUB_WORKSPACE

      #- name: Set permissions RUNNER_TEMP
      #  run: |
      #    ls -ld $RUNNER_TEMP
      #    sudo chown -R $(id -u):$(id -g) $RUNNER_TEMP
      #    ls -ld $RUNNER_TEMP
      #    ls -la $RUNNER_TEMP

      - name: Fix runner directory permissions
        run: sudo chown -R $(id -u):$(id -g) /__w

      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: hello-file
          path: ${{ github.workspace }}/hello.txt

      - name: Show current working directory
        #continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        #continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show CPU information
        #continue-on-error: true
        run: |
          echo "### CPU information:"
          lscpu

      - name: Show disk space
        #continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        #continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: du
        #continue-on-error: true
        run: |
          echo "### du:"
          sudo du -h --max-depth=1 / | sort -h -r

      - name: install
        #continue-on-error: true
        run: |
          echo "### install:"
          sudo apt-get update
          sudo apt-get dist-upgrade
          
          sudo echo "PATH: $PATH"
          sudo echo "ANDROID_HOME: $ANDROID_HOME"
          sudo echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          sudo echo "ANDROID_SDK: $ANDROID_SDK"
          sudo echo "ANDROID_NDK: $ANDROID_NDK"
          sudo echo "FDROIDSERVER: $FDROIDSERVER"
          sudo echo "PYTHONPATH: $PYTHONPATH"
          sudo echo "PYTHONUNBUFFERED: $PYTHONUNBUFFERED"
          #echo "GRADLE_OPTS: $GRADLE_OPTS"
          
          mkdir ${FDROIDSERVER}
          git ls-remote https://gitlab.com/fdroid/fdroidserver.git master
          curl --silent https://gitlab.com/fdroid/fdroidserver/-/archive/master/fdroidserver-master.tar.gz | tar -xz --directory=${FDROIDSERVER} --strip-components=1
          
          sudo apt-get install -y lsb-release tree
          #apt-get install -y ant g++ clang build-essential swig
          #apt-get install -y cmake automake zip
          #apt-get install -y byacc libpcre2-dev python-is-python3
          #apt-get install -y openjdk-17-jdk-headless
          sudo apt-get install -y openjdk-17-jdk-headless build-essential ant cmake clang python-is-python3 wget swig zip
          
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          which java
          which javac
          ls -la /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version
          javac -version

          which sdkmanager
          ls -l "$(which sdkmanager)"
          #cat "$(which sdkmanager)"

          #echo "HOME:" $HOME

          #export HOME=$(getent passwd $(whoami) | cut -d: -f6)
          #echo "HOME is now: $HOME"
          
          sdkmanager "platform-tools" "build-tools;31.0.0" "ndk;r23c"

          #HOME_TMP=$(getent passwd $(whoami) | cut -d: -f6)
          #echo "HOME_TMP: $HOME_TMP"
          #HOME=$HOME_TMP sdkmanager "platform-tools" "build-tools;31.0.0" "ndk;r23c"
          
          echo "### Disk space after install:"
          df -h

      - name: lsb_release
        #continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a
          cat /etc/passwd

      - name: fdroidserver path
        #continue-on-error: true
        run: |
          echo "### ls fdroidserver path:"
          ls -la "$FDROIDSERVER"

      - name: android-sdk path
        #continue-on-error: true
        run: |
          echo "### ls android-sdk path:"
          ls -la "$ANDROID_SDK"

      - name: android-ndk path
        #continue-on-error: true
        run: |
          echo "### ls android-ndk path:"
          ls -la "$ANDROID_NDK"

      - name: Show directory structure from root
        #continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 4:"
          sudo tree -L 4 / || true

      - name: build
        #continue-on-error: true
        run: |
          echo "### Build:"
          whoami
          pwd
          echo "PATH:"
          echo $PATH
          echo "ANDROID_HOME:"
          echo $ANDROID_HOME
          echo "ANDROID_SDK_ROOT:"
          echo $ANDROID_SDK_ROOT
          git clone --branch v5.1.5 --depth 1 https://github.com/fd-2025/OsmAnd-submodules.git #https://gitlab.com/f-droid-mirrors/OsmAnd-submodules.git
          cd OsmAnd-submodules
          git submodule init
          git submodule update --depth 1
          ls -la android/OsmAnd-java/libs/*.jar
          ls -la android/OsmAnd/libs/*.jar
          ls -la android/OsmAnd-telegram/
          ls -la resources/icons/tools/SVGtoXML/vd-tool
          rm -Rf android/OsmAnd-java/libs/*.jar
          rm -Rf android/OsmAnd/libs/*.jar
          rm -Rf android/OsmAnd-telegram/
          rm -Rf resources/icons/tools/SVGtoXML/vd-tool
          
          echo "### du begin:"
          du -h --max-depth=1 . | sort -h -r
          
          #HOME_TMP=$(getent passwd $(whoami) | cut -d: -f6)
          #echo "HOME_TMP: $HOME_TMP"
          #HOME=$HOME_TMP ./prebuild.sh "5.1.4" "510403" arm64
          ./prebuild.sh "5.1.4" "510403" arm64
          ./build.sh arm64
          
          echo "### Disk space mid build:"
          df -h
          du -h --max-depth=7 . | sort -h -r
          
          echo "### find build:"
          find . -type f -name "*.so"
          find . -type f -name "*.jar"
          find . -type f -name "*.aar"

          echo "### delete:"
          pwd
          rm -Rf core/externals/boost
          #rm -Rf core/wrappers/android/build/intermediates
          
          echo "### Disk space mid build 2:"
          df -h

      - name: build2
        #continue-on-error: true
        run: |
          echo "### Build2:"
          whoami
          pwd
          echo "PATH:"
          echo $PATH
          echo "ANDROID_HOME:"
          echo $ANDROID_HOME
          echo "ANDROID_SDK_ROOT:"
          echo $ANDROID_SDK_ROOT

          cd OsmAnd-submodules
          cd android/OsmAnd
          
          pwd
          
          gradle assembleAndroidFullOpenglArm64Release
          #gradle assembleAndroidFullOpenglArm64Release -x :OsmAnd-java:test
          
          echo "### Disk space after build:"
          df -h
          
          #echo "find all APKs:"
          #find / -type f -name '*.apk'
          echo "find APKs:"
          #find / -type f -name 'OsmAnd*.apk'
          find $GITHUB_WORKSPACE -type f -name 'OsmAnd*.apk'
          echo "find and copy APKs to workspace:"
          mkdir $GITHUB_WORKSPACE/output
          find $GITHUB_WORKSPACE -type f -name 'OsmAnd*.apk' -exec cp {} $GITHUB_WORKSPACE/output/ \;
          ls -l $GITHUB_WORKSPACE/output

      - name: Upload all APKs as an artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: ${{ github.workspace }}/output/
