name: fdroid build

on:
  push:
  workflow_dispatch:

jobs:
  show-system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        continue-on-error: true
        uses: actions/checkout@v4

      - name: whoami
        continue-on-error: true
        run: whoami

      - name: Show current working directory
        continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show disk space
        continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: lsb_release
        continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a

      - name: android-sdk path
        continue-on-error: true
        run: |
          echo "### android-sdk path:"
          ls -la /opt/android-sdk

      - name: apt
        continue-on-error: true
        run: |
          echo "### apt:"
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt-get install swig cmake lsb-release tree

      - name: Show directory structure from root
        continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 3:"
          tree -L 3 / || (sudo apt-get update && sudo apt-get install tree -y && tree -L 3 /)
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm

    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout repository
        continue-on-error: true
        uses: actions/checkout@v4

      - name: whoami
        continue-on-error: true
        run: whoami

      - name: Show current working directory
        continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show disk space
        continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: apt
        continue-on-error: true
        run: |
          echo "### apt:"
          apt-get update
          apt-get dist-upgrade
          apt-get install -y lsb-release tree
          apt-get install -y ant g++ clang build-essential swig
          apt-get install -y cmake automake zip
          apt-get install -y byacc libpcre2-dev python-is-python3

      - name: lsb_release
        continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a

      - name: fdroidserver path
        continue-on-error: true
        run: |
          echo "### fdroidserver path:"
          ls -la /home/vagrant/fdroidserver

      - name: android-sdk path
        continue-on-error: true
        run: |
          echo "### android-sdk path:"
          ls -la /opt/android-sdk
          sdkmanager "platform-tools" "build-tools;31.0.0"

      - name: Show directory structure from root
        continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 4:"
          tree -L 4
