name: fdroid build

on:
  push:
  workflow_dispatch:

jobs:
  show-system-info:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        continue-on-error: true
        uses: actions/checkout@v4

      - name: whoami
        continue-on-error: true
        run: whoami

      - name: Show current working directory
        continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show CPU information
        continue-on-error: true
        run: |
          echo "### CPU information:"
          lscpu

      - name: Show disk space
        continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: lsb_release
        continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a

      - name: apt
        continue-on-error: true
        run: |
          echo "### apt:"
          sudo apt-get update
          sudo apt-get dist-upgrade
          sudo apt-get install swig cmake lsb-release tree

      - name: Show directory structure from root
        continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 2:"
          tree -L 2 /
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm

    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout repository
        continue-on-error: true
        uses: actions/checkout@v4

      - name: whoami
        continue-on-error: true
        run: whoami

      - name: Show current working directory
        continue-on-error: true
        run: |
          echo "### Current working directory:"
          pwd

      - name: Show RAM information
        continue-on-error: true
        run: |
          echo "### RAM information:"
          free -h

      - name: Show CPU information
        continue-on-error: true
        run: |
          echo "### CPU information:"
          lscpu

      - name: Show disk space
        continue-on-error: true
        run: |
          echo "### Disk space:"
          df -h

      - name: uname
        continue-on-error: true
        run: |
          echo "### uname -a:"
          uname -a

      - name: apt
        continue-on-error: true
        run: |
          echo "### apt:"
          apt-get update
          apt-get dist-upgrade
          apt-get install -y lsb-release tree
          apt-get install -y ant g++ clang build-essential swig
          apt-get install -y cmake automake zip
          apt-get install -y byacc libpcre2-dev python-is-python3
          apt-get install -y openjdk-17-jdk-headless gradle
          update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          which java
          which javac
          ls -la /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version
          javac -version

      - name: lsb_release
        continue-on-error: true
        run: |
          echo "### lsb_release:"
          lsb_release -a
          cat /etc/passwd

      - name: fdroidserver path
        continue-on-error: true
        run: |
          echo "### fdroidserver path:"
          ls -la /home/vagrant/fdroidserver

      - name: android-sdk path
        continue-on-error: true
        run: |
          echo "### android-sdk path:"
          ls -la /opt/android-sdk
          sdkmanager "platform-tools" "build-tools;31.0.0" "ndk;r23c"

      - name: Show directory structure from root
        continue-on-error: true
        run: |
          echo "### Directory structure from root (/), depth 4:"
          tree -L 4 /

      - name: build
        continue-on-error: true
        run: |
          echo "### Build:"
          su vagrant
          whoami
          pwd
          git clone https://gitlab.com/f-droid-mirrors/OsmAnd-submodules.git
          cd OsmAnd-submodules
          git submodule init
          git submodule update
          ./prebuild.sh "5.1.2" "5102" arm64
          ./build.sh arm64
          cd android/Osmand
          gradle assembleAndroidFullOpenglArm64Release
