name: free

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          curl -sS -H Metadata:true "http://169.254.169.254/metadata/versions"
          echo -e "\nAzure VM:"
          curl -sS -H Metadata:true "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2023-11-15&format=text"
          whoami
          id
          df -h
          sudo tune2fs -m 0 "$(findmnt -n -o SOURCE --target /mnt)"
          df -h
          ls -la /mnt
          #sudo du -h --max-depth=5 / | sort -hr | head -n 50

          sudo du -sh /usr/local/lib/android || true
          sudo rm -rf /usr/local/lib/android

          sudo du -sh /usr/local/.ghcup || true
          sudo rm -rf /usr/local/.ghcup

          sudo du -sh /opt/hostedtoolcache || true
          sudo rm -rf /opt/hostedtoolcache
          df -h
