name: free

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          whoami
          id
          df -h
          ls -la /mnt
          sudo du -h --max-depth=5 / | sort -hr | head -n 50

          df -h
          echo "rm android"
          sudo du -sh /usr/local/lib/android || true
          sudo rm -rf /usr/local/lib/android
          df -h
          sudo du -sh /usr/local/.ghcup || true
          sudo rm -rf /usr/local/.ghcup
          echo "test1"
          sudo du -sh /usr12333 || true
          sudo rm -rf /usr12333
          echo "test2"
          df -h
          sudo du -sh /opt/hostedtoolcache || true
          sudo rm -rf /opt/hostedtoolcache
          df -h
