name: free

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          curl -sS -H Metadata:true "http://169.254.169.254/metadata/versions"
          echo -e "\nAzure VM:"
          curl -sS -H Metadata:true "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2023-11-15&format=text"
          whoami
          id
          df -h
          sudo tune2fs -m 0 "$(findmnt -n -o SOURCE --target /mnt)"
          df -h
          ls -la /mnt
          #sudo du -h --max-depth=5 / | sort -hr | head -n 50

          sudo du -sh /usr/local/lib/android || true
          sudo rm -rf /usr/local/lib/android

          sudo du -sh /usr/local/.ghcup || true
          sudo rm -rf /usr/local/.ghcup

          sudo du -sh /opt/hostedtoolcache || true
          sudo rm -rf /opt/hostedtoolcache
          df -h

          VG_NAME=buildvg
          BUILD_MOUNT_PATH=/mnt/data_volume
          ROOT_PV_PATH=/pv.img
          MNT_PV_PATH=/mnt/pv.img
          ROOT_BYTES=21474836480

          sudo mkdir -p "${BUILD_MOUNT_PATH}"

          echo "Creating LVM Volume"
          echo "-- Creating LVM PV on root fs"
          # create loop pv image on root fs
          sudo touch "${ROOT_PV_PATH}" && sudo fallocate -z -l "${ROOT_BYTES}" "${ROOT_PV_PATH}"
          export ROOT_LOOP_DEV=$(sudo losetup --find --show "${ROOT_PV_PATH}")
          sudo pvcreate -f "${ROOT_LOOP_DEV}"

          # create pv on mnt disk
          echo "-- Creating LVM PV on mnt fs"
          
          MNT_RESERVE_KB=131072
          MNT_FREE_KB=$(df --block-size=1024 --output=avail /mnt | tail -1)
          MNT_LVM_SIZE_KB=$(expr $MNT_FREE_KB - $MNT_RESERVE_KB)
          MNT_LVM_SIZE_BYTES=$(expr $MNT_LVM_SIZE_KB \* 1024)
          
          sudo touch "${MNT_PV_PATH}" && sudo fallocate -z -l "${MNT_LVM_SIZE_BYTES}" "${MNT_PV_PATH}"
          export MNT_LOOP_DEV=$(sudo losetup --find --show "${MNT_PV_PATH})
          sudo pvcreate -f "${MNT_LOOP_DEV}"

          # create volume group from these pvs
          sudo vgcreate "${VG_NAME}" "${MNT_LOOP_DEV}" "${ROOT_LOOP_DEV}"

          echo "Creating build volume"
          # create and mount build volume
          sudo lvcreate -l 100%FREE -n buildlv "${VG_NAME}"
          sudo mkfs.ext4 -Enodiscard -m0 "/dev/mapper/${VG_NAME}-buildlv"
          sudo mount "/dev/mapper/${VG_NAME}-buildlv" "${BUILD_MOUNT_PATH}"

          df -h
